HEADERS += \
    xflwidgets/color/colorbtn.h \
    xflwidgets/color/colorgraddlg.h \
    xflwidgets/color/textclrbtn.h \
    xflwidgets/customdlg/doublevaluedlg.h \
    xflwidgets/customdlg/gridsettingsdlg.h \
    xflwidgets/customdlg/helpimgdlg.h \
    xflwidgets/customdlg/imagedlg.h \
    xflwidgets/customdlg/intvaluedlg.h \
    xflwidgets/customdlg/intvaluesdlg.h \
    xflwidgets/customdlg/logmessagedlg.h \
    xflwidgets/customdlg/moddlg.h \
    xflwidgets/customdlg/newnamedlg.h \
    xflwidgets/customdlg/objectpropsdlg.h \
    xflwidgets/customdlg/renamedlg.h \
    xflwidgets/customdlg/selectiondlg.h \
    xflwidgets/customdlg/separatorsdlg.h \
    xflwidgets/customdlg/stringvaluedlg.h \
    xflwidgets/customdlg/textdlg.h \
    xflwidgets/customdlg/xfldialog.h \
    xflwidgets/customdlg/xflfiledialog.h \
    xflwidgets/customwts/actionitemmodel.h \
    xflwidgets/customwts/cptableview.h \
    xflwidgets/customwts/crosscheckbox.h \
    xflwidgets/customwts/ctrltabledelegate.h \
    xflwidgets/customwts/exponentialslider.h \
    xflwidgets/customwts/floatedit.h \
    xflwidgets/customwts/gridcontrol.h \
    xflwidgets/customwts/intedit.h \
    xflwidgets/customwts/numedit.h \
    xflwidgets/customwts/plaintextoutput.h \
    xflwidgets/customwts/popup.h \
    xflwidgets/customwts/xfldelegate.h \
    xflwidgets/customwts/xfltreeview.h \
    xflwidgets/line/legendbtn.h \
    xflwidgets/line/lineaction.h \
    xflwidgets/line/linebtn.h \
    xflwidgets/line/linecbbox.h \
    xflwidgets/line/linemenu.h \
    xflwidgets/line/linepicker.h \
    xflwidgets/mvc/expandabletreeview.h \
    xflwidgets/mvc/objecttreedelegate.h \
    xflwidgets/mvc/objecttreeitem.h \
    xflwidgets/mvc/objecttreemodel.h \
    xflwidgets/view/grid.h \
    xflwidgets/view/section2doptions.h \
    xflwidgets/view/section2dwt.h \
    xflwidgets/wt_globals.h \


SOURCES += \
    xflwidgets/color/colorbtn.cpp \
    xflwidgets/color/colorgraddlg.cpp \
    xflwidgets/color/textclrbtn.cpp \
    xflwidgets/customdlg/doublevaluedlg.cpp \
    xflwidgets/customdlg/gridsettingsdlg.cpp \
    xflwidgets/customdlg/helpimgdlg.cpp \
    xflwidgets/customdlg/imagedlg.cpp \
    xflwidgets/customdlg/intvaluedlg.cpp \
    xflwidgets/customdlg/intvaluesdlg.cpp \
    xflwidgets/customdlg/logmessagedlg.cpp \
    xflwidgets/customdlg/moddlg.cpp \
    xflwidgets/customdlg/newnamedlg.cpp \
    xflwidgets/customdlg/objectpropsdlg.cpp \
    xflwidgets/customdlg/renamedlg.cpp \
    xflwidgets/customdlg/selectiondlg.cpp \
    xflwidgets/customdlg/separatorsdlg.cpp \
    xflwidgets/customdlg/stringvaluedlg.cpp \
    xflwidgets/customdlg/textdlg.cpp \
    xflwidgets/customdlg/xfldialog.cpp \
    xflwidgets/customdlg/xflfiledialog.cpp \
    xflwidgets/customwts/actionitemmodel.cpp \
    xflwidgets/customwts/cptableview.cpp \
    xflwidgets/customwts/crosscheckbox.cpp \
    xflwidgets/customwts/ctrltabledelegate.cpp \
    xflwidgets/customwts/exponentialslider.cpp \
    xflwidgets/customwts/floatedit.cpp \
    xflwidgets/customwts/gridcontrol.cpp \
    xflwidgets/customwts/intedit.cpp \
    xflwidgets/customwts/numedit.cpp \
    xflwidgets/customwts/plaintextoutput.cpp \
    xflwidgets/customwts/popup.cpp \
    xflwidgets/customwts/xfldelegate.cpp \
    xflwidgets/customwts/xfltreeview.cpp \
    xflwidgets/line/legendbtn.cpp \
    xflwidgets/line/lineaction.cpp \
    xflwidgets/line/linebtn.cpp \
    xflwidgets/line/linecbbox.cpp \
    xflwidgets/line/linemenu.cpp \
    xflwidgets/line/linepicker.cpp \
    xflwidgets/mvc/expandabletreeview.cpp \
    xflwidgets/mvc/objecttreedelegate.cpp \
    xflwidgets/mvc/objecttreeitem.cpp \
    xflwidgets/mvc/objecttreemodel.cpp \
    xflwidgets/view/grid.cpp \
    xflwidgets/view/section2doptions.cpp \
    xflwidgets/view/section2dwt.cpp \
    xflwidgets/wt_globals.cpp \


RESOURCES += \
    xflwidgets/textfiles.qrc
